// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	sso "github.com/alibabacloud-go/cloudsso-20210515/client"
	mock "github.com/stretchr/testify/mock"
)

// SsoClient is a mock type for the ssoClient type
type SsoClient struct {
	mock.Mock
}

func (_m *SsoClient) ListGroups(request *sso.ListGroupsRequest) (*sso.ListGroupsResponse, error) {
	ret := _m.Called(request)
	return firstArgResp[*sso.ListGroupsResponse](ret), ret.Error(1)
}

func (_m *SsoClient) AddUserToGroup(request *sso.AddUserToGroupRequest) (*sso.AddUserToGroupResponse, error) {
	ret := _m.Called(request)
	return firstArgResp[*sso.AddUserToGroupResponse](ret), ret.Error(1)
}

func (_m *SsoClient) RemoveUserFromGroup(request *sso.RemoveUserFromGroupRequest) (*sso.RemoveUserFromGroupResponse, error) {
	ret := _m.Called(request)
	return firstArgResp[*sso.RemoveUserFromGroupResponse](ret), ret.Error(1)
}

func (_m *SsoClient) ListAccessConfigurations(request *sso.ListAccessConfigurationsRequest) (*sso.ListAccessConfigurationsResponse, error) {
	ret := _m.Called(request)
	return firstArgResp[*sso.ListAccessConfigurationsResponse](ret), ret.Error(1)
}

func (_m *SsoClient) AddPermissionPolicyToAccessConfiguration(request *sso.AddPermissionPolicyToAccessConfigurationRequest) (*sso.AddPermissionPolicyToAccessConfigurationResponse, error) {
	ret := _m.Called(request)
	return firstArgResp[*sso.AddPermissionPolicyToAccessConfigurationResponse](ret), ret.Error(1)
}

func (_m *SsoClient) RemovePermissionPolicyFromAccessConfiguration(request *sso.RemovePermissionPolicyFromAccessConfigurationRequest) (*sso.RemovePermissionPolicyFromAccessConfigurationResponse, error) {
	ret := _m.Called(request)
	return firstArgResp[*sso.RemovePermissionPolicyFromAccessConfigurationResponse](ret), ret.Error(1)
}

func (_m *SsoClient) ProvisionAccessConfiguration(request *sso.ProvisionAccessConfigurationRequest) (*sso.ProvisionAccessConfigurationResponse, error) {
	ret := _m.Called(request)
	return firstArgResp[*sso.ProvisionAccessConfigurationResponse](ret), ret.Error(1)
}

func (_m *SsoClient) GetTaskStatus(request *sso.GetTaskStatusRequest) (*sso.GetTaskStatusResponse, error) {
	ret := _m.Called(request)
	return firstArgResp[*sso.GetTaskStatusResponse](ret), ret.Error(1)
}

func (_m *SsoClient) ListAccessConfigurationProvisionings(request *sso.ListAccessConfigurationProvisioningsRequest) (*sso.ListAccessConfigurationProvisioningsResponse, error) {
	ret := _m.Called(request)
	return firstArgResp[*sso.ListAccessConfigurationProvisioningsResponse](ret), ret.Error(1)
}

// firstArgResp returns the first return argument typed as T, or nil if unset.
func firstArgResp[T any](ret mock.Arguments) T {
	var zero T
	if v := ret.Get(0); v != nil {
		return v.(T)
	}
	return zero
}

// NewSsoClient creates a new instance of SsoClient and registers a cleanup to
// assert its expectations.
func NewSsoClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SsoClient {
	m := &SsoClient{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
