// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Decryptor is an autogenerated mock type for the Decryptor type
type Decryptor struct {
	mock.Mock
}

type Decryptor_Expecter struct {
	mock *mock.Mock
}

func (_m *Decryptor) EXPECT() *Decryptor_Expecter {
	return &Decryptor_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function with given fields: _a0
func (_m *Decryptor) Decrypt(_a0 string) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Decryptor_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type Decryptor_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - _a0 string
func (_e *Decryptor_Expecter) Decrypt(_a0 interface{}) *Decryptor_Decrypt_Call {
	return &Decryptor_Decrypt_Call{Call: _e.mock.On("Decrypt", _a0)}
}

func (_c *Decryptor_Decrypt_Call) Run(run func(_a0 string)) *Decryptor_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Decryptor_Decrypt_Call) Return(_a0 string, _a1 error) *Decryptor_Decrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Decryptor_Decrypt_Call) RunAndReturn(run func(string) (string, error)) *Decryptor_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewDecryptor interface {
	mock.TestingT
	Cleanup(func())
}

// NewDecryptor creates a new instance of Decryptor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDecryptor(t mockConstructorTestingTNewDecryptor) *Decryptor {
	mock := &Decryptor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
