project_name: guardian
release:
  prerelease: auto
before:
  hooks:
    - go mod tidy
    - make clean
builds:
  - id: "guardian"
    main: ./main.go
    binary: guardian
    flags:
      - -a
    ldflags:
      - -X github.com/goto/guardian/core.Version={{.Tag}}
      - -X github.com/goto/guardian/core.BuildCommit={{.FullCommit}}
      - -X github.com/goto/guardian/core.BuildDate={{.Date}}
    goos: [darwin, linux, windows]
    goarch: [amd64, 386, arm, arm64]
    env:
      - CGO_ENABLED=0
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "linux" }}linux
      {{- else if eq .Arch "windows" }}windows
      {{- else if eq .Arch "darwin" }}macos
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^build:"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - guardian
    dockerfile: Dockerfile
    image_templates:
      - "docker.io/gotocompany/{{.ProjectName}}:latest"
      - "docker.io/gotocompany/{{.ProjectName}}:{{ .Version }}"
      - "docker.io/gotocompany/{{.ProjectName}}:{{ .Tag }}-amd64"
nfpms:
  - maintainer: gotocompany
    description: Universal data access tool
    homepage: https://github.com/goto/guardian
    license: Apache 2.0
    formats:
      - deb
      - rpm
    file_name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "darwin" }}macos{{- else }}{{ .Arch }}{{ end }}
scoop:
  bucket:
    owner: goto
    name: scoop-bucket
  homepage: "https://github.com/goto/guardian"
  description: "Universal data access tool"
  license: Apache 2.0
brews:
  - name: guardian
    homepage: "https://github.com/goto/guardian"
    description: "Universal data access tool"
    tap:
      owner: goto
      name: homebrew-tap
    license: "Apache 2.0"
    folder: Formula
    dependencies:
      - name: git
    install: |-
      bin.install "guardian"
    commit_author:
      name: github-actions[bot]
      email: 41898282+github-actions[bot]@users.noreply.github.com
