// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import (
	context "context"

	report "github.com/goto/guardian/core/report"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// GetPendingApprovalsList provides a mock function with given fields: ctx, filters
func (_m *Repository) GetPendingApprovalsList(ctx context.Context, filters *report.PendingApprovalsReportFilter) ([]*report.PendingApprovalModel, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingApprovalsList")
	}

	var r0 []*report.PendingApprovalModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *report.PendingApprovalsReportFilter) ([]*report.PendingApprovalModel, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *report.PendingApprovalsReportFilter) []*report.PendingApprovalModel); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*report.PendingApprovalModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *report.PendingApprovalsReportFilter) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetPendingApprovalsList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingApprovalsList'
type Repository_GetPendingApprovalsList_Call struct {
	*mock.Call
}

// GetPendingApprovalsList is a helper method to define mock.On call
//   - ctx context.Context
//   - filters *report.PendingApprovalsReportFilter
func (_e *Repository_Expecter) GetPendingApprovalsList(ctx interface{}, filters interface{}) *Repository_GetPendingApprovalsList_Call {
	return &Repository_GetPendingApprovalsList_Call{Call: _e.mock.On("GetPendingApprovalsList", ctx, filters)}
}

func (_c *Repository_GetPendingApprovalsList_Call) Run(run func(ctx context.Context, filters *report.PendingApprovalsReportFilter)) *Repository_GetPendingApprovalsList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*report.PendingApprovalsReportFilter))
	})
	return _c
}

func (_c *Repository_GetPendingApprovalsList_Call) Return(_a0 []*report.PendingApprovalModel, _a1 error) *Repository_GetPendingApprovalsList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetPendingApprovalsList_Call) RunAndReturn(run func(context.Context, *report.PendingApprovalsReportFilter) ([]*report.PendingApprovalModel, error)) *Repository_GetPendingApprovalsList_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
