// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/goto/guardian/domain"
	mock "github.com/stretchr/testify/mock"
)

// GrantService is an autogenerated mock type for the grantService type
type GrantService struct {
	mock.Mock
}

type GrantService_Expecter struct {
	mock *mock.Mock
}

func (_m *GrantService) EXPECT() *GrantService_Expecter {
	return &GrantService_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx, filter
func (_m *GrantService) List(ctx context.Context, filter domain.ListGrantsFilter) ([]domain.Grant, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Grant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListGrantsFilter) ([]domain.Grant, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ListGrantsFilter) []domain.Grant); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Grant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ListGrantsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GrantService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type GrantService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.ListGrantsFilter
func (_e *GrantService_Expecter) List(ctx interface{}, filter interface{}) *GrantService_List_Call {
	return &GrantService_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *GrantService_List_Call) Run(run func(ctx context.Context, filter domain.ListGrantsFilter)) *GrantService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ListGrantsFilter))
	})
	return _c
}

func (_c *GrantService_List_Call) Return(_a0 []domain.Grant, _a1 error) *GrantService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GrantService_List_Call) RunAndReturn(run func(context.Context, domain.ListGrantsFilter) ([]domain.Grant, error)) *GrantService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewGrantService creates a new instance of GrantService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGrantService(t interface {
	mock.TestingT
	Cleanup(func())
}) *GrantService {
	mock := &GrantService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
