// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/goto/guardian/domain"
	mock "github.com/stretchr/testify/mock"
)

// ShieldResourceService is an autogenerated mock type for the shield.ResourceService type
type ShieldResourceService struct {
	mock.Mock
}

type ShieldResourceService_Expecter struct {
	mock *mock.Mock
}

func (_m *ShieldResourceService) EXPECT() *ShieldResourceService_Expecter {
	return &ShieldResourceService_Expecter{mock: &_m.Mock}
}

// BulkUpsert provides a mock function with given fields: _a0, _a1
func (_m *ShieldResourceService) BulkUpsert(_a0 context.Context, _a1 []*domain.Resource) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*domain.Resource) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ShieldResourceService_BulkUpsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpsert'
type ShieldResourceService_BulkUpsert_Call struct {
	*mock.Call
}

// BulkUpsert is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []*domain.Resource
func (_e *ShieldResourceService_Expecter) BulkUpsert(_a0 interface{}, _a1 interface{}) *ShieldResourceService_BulkUpsert_Call {
	return &ShieldResourceService_BulkUpsert_Call{Call: _e.mock.On("BulkUpsert", _a0, _a1)}
}

func (_c *ShieldResourceService_BulkUpsert_Call) Run(run func(_a0 context.Context, _a1 []*domain.Resource)) *ShieldResourceService_BulkUpsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*domain.Resource))
	})
	return _c
}

func (_c *ShieldResourceService_BulkUpsert_Call) Return(_a0 error) *ShieldResourceService_BulkUpsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ShieldResourceService_BulkUpsert_Call) RunAndReturn(run func(context.Context, []*domain.Resource) error) *ShieldResourceService_BulkUpsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewShieldResourceService creates a new instance of ShieldResourceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShieldResourceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShieldResourceService {
	mock := &ShieldResourceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
