jobs:
  - type: bot_expiration_alert
    config:
      reminder_in_days: [15, 7, 3, 1]
      critical_threshold_in_days: 3
      environment: "production"
      iam:
        provider: "shield"
        config:
          host: "http://shield.com"
          auth_header: "X-Auth-Email"
          auth_email: "username@email.com"
      extract_bot_email: "$grant?.appeal?.details?.__policy_metadata?.ram_user_details?.user_principal_name"
      filters:
        account_types:
          - "bot"
        provider_types:
          - "guardian"
        resource_ids:
          - "58658af9-bf57-48ab-8553-d1b5527e1ff4"
        account_ids:
          - "RAM$123456789:987654321"
          - "RAM$123456789:987654322"