// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/goto/guardian/domain"

	mock "github.com/stretchr/testify/mock"
)

// AlertManager is an autogenerated mock type for the alertManager type
type AlertManager struct {
	mock.Mock
}

type AlertManager_Expecter struct {
	mock *mock.Mock
}

func (_m *AlertManager) EXPECT() *AlertManager_Expecter {
	return &AlertManager_Expecter{mock: &_m.Mock}
}

// NotifyDriftCheck provides a mock function with given fields: ctx, adminTeam, issues
func (_m *AlertManager) NotifyDriftCheck(ctx context.Context, adminTeam string, issues []domain.GrantDriftIssue) []error {
	ret := _m.Called(ctx, adminTeam, issues)

	if len(ret) == 0 {
		panic("no return value specified for NotifyDriftCheck")
	}

	var r0 []error
	if rf, ok := ret.Get(0).(func(context.Context, string, []domain.GrantDriftIssue) []error); ok {
		r0 = rf(ctx, adminTeam, issues)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]error)
		}
	}

	return r0
}

// AlertManager_NotifyDriftCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyDriftCheck'
type AlertManager_NotifyDriftCheck_Call struct {
	*mock.Call
}

// NotifyDriftCheck is a helper method to define mock.On call
//   - ctx context.Context
//   - adminTeam string
//   - issues []domain.GrantDriftIssue
func (_e *AlertManager_Expecter) NotifyDriftCheck(ctx interface{}, adminTeam interface{}, issues interface{}) *AlertManager_NotifyDriftCheck_Call {
	return &AlertManager_NotifyDriftCheck_Call{Call: _e.mock.On("NotifyDriftCheck", ctx, adminTeam, issues)}
}

func (_c *AlertManager_NotifyDriftCheck_Call) Run(run func(ctx context.Context, adminTeam string, issues []domain.GrantDriftIssue)) *AlertManager_NotifyDriftCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]domain.GrantDriftIssue))
	})
	return _c
}

func (_c *AlertManager_NotifyDriftCheck_Call) Return(_a0 []error) *AlertManager_NotifyDriftCheck_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AlertManager_NotifyDriftCheck_Call) RunAndReturn(run func(context.Context, string, []domain.GrantDriftIssue) []error) *AlertManager_NotifyDriftCheck_Call {
	_c.Call.Return(run)
	return _c
}

// NewAlertManager creates a new instance of AlertManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlertManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *AlertManager {
	mock := &AlertManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
