// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/goto/guardian/domain"
	mock "github.com/stretchr/testify/mock"
)

// AppealService is an autogenerated mock type for the appealService type
type AppealService struct {
	mock.Mock
}

type AppealService_Expecter struct {
	mock *mock.Mock
}

func (_m *AppealService) EXPECT() *AppealService_Expecter {
	return &AppealService_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *AppealService) GetByID(ctx context.Context, id string) (*domain.Appeal, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Appeal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Appeal, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Appeal); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Appeal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AppealService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type AppealService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *AppealService_Expecter) GetByID(ctx interface{}, id interface{}) *AppealService_GetByID_Call {
	return &AppealService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *AppealService_GetByID_Call) Run(run func(ctx context.Context, id string)) *AppealService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AppealService_GetByID_Call) Return(_a0 *domain.Appeal, _a1 error) *AppealService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AppealService_GetByID_Call) RunAndReturn(run func(context.Context, string) (*domain.Appeal, error)) *AppealService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewAppealService creates a new instance of AppealService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppealService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppealService {
	mock := &AppealService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
